 on:
  push:
    branches:
    - main
    - release/*
    
    on:    
  pull_request:
    branches:
    - main


on:
  schedule:
  - cron: "0 2 * * 1-5"

 workflow_dispatch 
  on:
  workflow_dispatch:

  runs-on:

  jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-22.04

    ubuntu-latest, ubuntu-22.04, or ubuntu-20.04
windows-latest, windows-2022, or windows-2019
macos-latest, macos-13, or macos-12

- name: Setup Node
  uses: actions/setup-node@v4
  with:
    node-version: '20.x'

    - name: Install Dependencies
  run: npm install

